### ISSUE TITLE
Add date information to event listings

### ISSUE THREAD

**Issue by DT359** [matthuisman/plugin.video.kayo.sports#2]
As a user of Kayo Kodi app, I want to be able to quickly tell which game in a list occurred on which day (to not watch a more recent game that might spoil the result of the earlier one (e.g. from commentary). Additionally, as Kayo doesn't advise when content expires, it is useful to watch a game that will expire sooner first.

For past events, append the date it occurred. e.g. dd-Mmm
For future events, add the day and time it will commence. e.g dd-Mmm hh:mm [AM/PM]
Could substitute 'Yesterday', 'Today' and 'Tomorrow' for the date as applicable.

This information should hopefully be accessible as the official Kayo app uses this information.
![kayo kodi current](https://user-images.githubusercontent.com/7701378/54812888-58571c80-4ce0-11e9-8553-2cc7938e7009.png)
![kayo kodi suggested](https://user-images.githubusercontent.com/7701378/54812890-58efb300-4ce0-11e9-8216-63f009602b24.png)
![kayo UI](https://user-images.githubusercontent.com/7701378/54812891-58efb300-4ce0-11e9-9888-ea1e2be54486.PNG)

**Comment by matthuisman** [comment]
Done in version 0.2.4 of the add-on (just pushed)
